---
kind: pipeline
type: docker
name: Build Nginx modules

platform:
  os: linux
  arch: amd64

steps:
  - name: Ubuntu 20.04
    image: ubuntu:focal
    commands:
    - ln -snf /usr/share/zoneinfo/CET /etc/localtime && echo CET > /etc/timezone
    - ./compile_nginx.sh
    
- name: scp files
image: appleboy/drone-scp
settings:
  host:
    from_secret: target_server
  user: root
  key:
    from_secret: ssh_key
  port: 22
  command_timeout: 2m
  target: /root/
  source:
    - ./modules.tar.gz